CREATE TABLE IF NOT EXISTS BOOK
(
    ID    BIGINT    AUTO_INCREMENT    PRIMARY    KEY,
    TITLE    VARCHAR(255) NOT NULL,
    AUTHOR VARCHAR(255) NOT NULL,
    PUBLICATION_YEAR INT NOT NULL,
    ISBN VARCHAR(255),
    AVAILABLE_FOR_BORROWING VARCHAR(5) DEFAULT 'TRUE'
    );

CREATE TABLE IF NOT EXISTS BORROWING_RECORD
(
    ID    BIGINT    AUTO_INCREMENT    PRIMARY    KEY,
    BOOK_ID  BIGINT NOT NULL,
    PATRON_ID BIGINT NOT NULL,
    BORROWING_DATE DATE ,
    RETURN_DATE DATE
    );

CREATE TABLE IF NOT EXISTS PATRON
(
    ID    BIGINT    AUTO_INCREMENT    PRIMARY    KEY,
    NAME  VARCHAR(255) NOT NULL,
    CONTACT_INFORMATION VARCHAR(255) NOT NULL
);
